export const SET_CURRENT_PASSWORD = 'SET_CURRENT_PASSWORD'
export const SET_10_LAST_FINISHED_PASSWORDS = 'SET_10_LAST_FINISHED_PASSWORDS'
export const SET_IN_PROGRESS_PASSWORDS = 'SET_IN_PROGRESS_PASSWORDS'
export const SET_ALL_PASSWORDS = 'SET_ALL_PASSWORDS'
export const LOADING_ALL_PASSWORDS = 'LOADING_ALL_PASSWORDS'

export const SET_USERS = 'SET_USERS'
export const LOADING_USERS = 'LOADING_USERS'

export const SET_PASSWORD_CATEGORIES = 'SET_PASSWORD_CATEGORIES'
export const LOADING_PASSWORD_CATEGORIES = 'LOADING_PASSWORD_CATEGORIES'

