export const ADD_IN_PROGRESS_PASSWORDS = 'ADD_IN_PROGRESS_PASSWORDS'
export const ADD_10_LAST_FINISHED_PASSWORDS = 'ADD_10_LAST_FINISHED_PASSWORDS'
export const ADD_CURRENT_PASSWORD = 'ADD_CURRENT_PASSWORD'

export const SET_USERS = 'SET_USERS'
